"""Add language and published_date columns to article model

Revision ID: 329ca6aec6df
Revises: c64f55bf5769
Create Date: 2024-11-02 22:28:16.792072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329ca6aec6df'
down_revision: Union[str, None] = 'c64f55bf5769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('article', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('language', sa.String(length=3), nullable=True))
    op.add_column('articles', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.drop_column('articles', 'article_german')
    op.drop_column('articles', 'title_english')
    op.drop_column('articles', 'article_english')
    op.drop_column('articles', 'title_german')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title_german', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('article_english', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('title_english', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('article_german', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'published_date')
    op.drop_column('articles', 'language')
    op.drop_column('articles', 'article')
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
