"""Fix article_entity_sentiment_topics table

Revision ID: 7b5cd6fd85a4
Revises: 2fa13fe70acd
Create Date: 2024-11-02 00:57:03.342056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b5cd6fd85a4'
down_revision: Union[str, None] = '2fa13fe70acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_entity_sentiment_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['sentiment_id'], ['sentiments.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('article_entity_sentiment_aspects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_entity_sentiment_aspects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sentiment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_entity_sentiment_aspects_article_id_fkey'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name='article_entity_sentiment_aspects_entity_id_fkey'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name='article_entity_sentiment_aspects_model_id_fkey'),
    sa.ForeignKeyConstraint(['sentiment_id'], ['sentiments.id'], name='article_entity_sentiment_aspects_sentiment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='article_entity_sentiment_aspects_pkey')
    )
    op.drop_table('article_entity_sentiment_topics')
    # ### end Alembic commands ###
