"""Add column name to entity_mentions table

Revision ID: 965997425db6
Revises: 7bec980b3e8d
Create Date: 2024-11-11 20:44:39.757617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965997425db6'
down_revision: Union[str, None] = '7bec980b3e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_mentions', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_mentions', 'name')
    # ### end Alembic commands ###
