"""Change embedding size

Revision ID: c64f55bf5769
Revises: 7b5cd6fd85a4
Create Date: 2024-11-02 01:14:40.160793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'c64f55bf5769'
down_revision: Union[str, None] = '7b5cd6fd85a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entities', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.alter_column('entity_mentions', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.alter_column('sentiments', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.alter_column('topics', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    op.alter_column('sentiments', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    op.alter_column('entity_mentions', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    op.alter_column('entities', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###
