"""add column similarity to entity_mentions table

Revision ID: ce7299fb3e98
Revises: 965997425db6
Create Date: 2024-11-14 21:20:09.466482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7299fb3e98'
down_revision: Union[str, None] = '965997425db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_mentions', sa.Column('similarity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_mentions', 'similarity')
    # ### end Alembic commands ###
