"""change confidence and similarity to float

Revision ID: d0ff07781f64
Revises: ce7299fb3e98
Create Date: 2024-11-14 22:37:20.572914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ff07781f64'
down_revision: Union[str, None] = 'ce7299fb3e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_mentions', 'confidence',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('entity_mentions', 'similarity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_mentions', 'similarity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('entity_mentions', 'confidence',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
